### ISSUE TITLE
Integration: gnome extensions

### ISSUE THREAD

**Issue by ChappIO** [ChappIO/dashfiles#5]
Using the `chrome-gnome-shell` application it is possible to list and install extensions.

It would be nice to have this support as a package manager.

Example: gnome-extensions.packages
```
# Top Icons
TopIcons@phocean.net

# Native Window Placement
native-window-placement@gnome-shell-extensions.gcampax.github.com
```

**Comment by LucaScorpion** [comment]
Example command to get a list of all extensions using the `chrome-gnome-shell`:  
```
printf '\x0\x0\x0\x1A{"execute":"listExtensions"}'
```

The first part (`\x0\x0\x0\x1A`) are 4 bytes which cointain the length of the message (in this case 26, or 1A in hex). The rest of the message is a json object. See also:  
https://github.com/GNOME/chrome-gnome-shell/blob/master/connector/chrome-gnome-shell.py
